CREATE TABLE IF NOT EXISTS applications
(
    root_id                        INT8 PRIMARY KEY,
    version_id                     INT8             NOT NULL,
    number                         TEXT             NOT NULL,
    created_at                     TIMESTAMPTZ      NOT NULL,
    version_started_at             TIMESTAMPTZ      NOT NULL,
    is_incident                    BOOL             NULL,
    parent_root_id                 int8             NULL,
    user_last_edited               TEXT             NOT NULL,
    user_last_edited_organization  TEXT             NOT NULL,
    comment                        TEXT             NOT NULL,
    category_id                    INT4             NOT NULL,
    defect_id                      INT4             NOT NULL,
    is_defect_returnable           BOOL             NOT NULL,
    applicant_description          TEXT             NOT NULL,
    applicant_question             TEXT             NOT NULL,
    emergency_type                 TEXT             NOT NULL,
    region                         TEXT             NOT NULL,
    district                       TEXT             NOT NULL,
    address                        TEXT             NOT NULL,
    unom                           INT4             NOT NULL,
    entrance                       TEXT             NULL,
    floor                          TEXT             NULL,
    flat                           TEXT             NULL,
    ods_number                     TEXT             NOT NULL,
    management_company_title       TEXT             NOT NULL,
    execution_company_title        TEXT             NOT NULL,
    rendered_services_ids          INT4[]           NOT NULL,
    consumed_materials             TEXT             NULL,
    rendered_security_services_ids INT4[]           NOT NULL,
    result_code                    TEXT             NOT NULL,
    amount_of_returnings           INT2             NOT NULL DEFAULT 0,
    last_returned_at               TIMESTAMPTZ      NULL,
    is_alarmed                     BOOL             NOT NULL,
    closed_at                      TIMESTAMPTZ      NOT NULL,
    preferable_from                TIMESTAMPTZ      NULL,
    preferable_to                  TIMESTAMPTZ      NULL,
    rated_at                       TIMESTAMPTZ      NULL,
    review                         TEXT             NULL,
    rating_code                    TEXT             NULL,

    is_abnormal                    BOOL             NULL,
    anomaly_classes                JSONB            NULL
);